CREATE TABLE users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100),
 email VARCHAR(100)
);

CREATE TABLE transactions (
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT,
 amount DECIMAL(10,2),
 type VARCHAR(20),
 FOREIGN KEY (user_id) REFERENCES users(id)
);